/*
 *  This file is part of the Jikes RVM project (http://jikesrvm.org).
 *
 *  This file is licensed to You under the Eclipse Public License (EPL);
 *  You may not use this file except in compliance with the License. You
 *  may obtain a copy of the License at
 *
 *      http://www.opensource.org/licenses/eclipse-1.0.php
 *
 *  See the COPYRIGHT.txt file distributed with this work for information
 *  regarding copyright ownership.
 */
 
/*
 * Test synchronization barriers
 */
void main() {
  spawn(thread);
  spawn(thread);
  barrierWait("finish",3);
  print("Exit");
}


void thread() {
  barrierWait("begin",2);
  print("Reached barrier <begin>");
  int ordinal = barrierWait("end",2);
  if (ordinal == 1) {
    print("First thread");
  }
  barrierWait("finish",3);
}