/*
 *  This file is part of the Jikes RVM project (http://jikesrvm.org).
 *
 *  This file is licensed to You under the Eclipse Public License (EPL);
 *  You may not use this file except in compliance with the License. You
 *  may obtain a copy of the License at
 *
 *      http://www.opensource.org/licenses/eclipse-1.0.php
 *
 *  See the COPYRIGHT.txt file distributed with this work for information
 *  regarding copyright ownership.
 */
void main() {
  check (f(),1);
  check (g(1),3);
  check (g(2*3),13);
  check (g(g(f())),7);
}

check(int actual, int expected) {
  if (actual == expected) {
    print("OK");
  } else {
    print("ERROR");
  }
}

int f() {
  return 1;
}

int g(int i) {
  return i * 2 + 1;
}
