/*
 *  This file is part of the Jikes RVM project (http://jikesrvm.org).
 *
 *  This file is licensed to You under the Eclipse Public License (EPL);
 *  You may not use this file except in compliance with the License. You
 *  may obtain a copy of the License at
 *
 *      http://www.opensource.org/licenses/eclipse-1.0.php
 *
 *  See the COPYRIGHT.txt file distributed with this work for information
 *  regarding copyright ownership.
 */
void main() {
  print("0 + 1 = ",0 + 1," : ",(0 + 1) == 1);
  print("0 * 1 = ",0 * 1," : ",(0 * 1) == 0);
  print("0 - 1 = ",0 - 1," : ",(0 - 1) == (-1));
  print("4 / 2 = ",4 / 2," : ",(4 / 2) == 2);
  print("5 % 3 = ",5 % 3," : ",(5 % 3) == 2);
  print("1 + 2 * 3 = ",1 + 2 * 3," : ",(1 + 2 * 3) == 7);
  print("1 * 2 + 3 = ",1 * 2 + 3," : ",(1 * 2 + 3) == 5);
  print("4 / 2 + 3 = ",4 / 2 + 3," : ",(4 / 2 + 3) == 5);
  print("1 * 2 + 3 * 4 = ",1 * 2 + 3 * 4," : ",(1 * 2 + 3 * 4) == 14);
  print("(1 + 2) * (3 + 4) = ",(1 + 2) * (3 + 4)," : ",((1 + 2) * (3 + 4)) == 21);
}
