/*
 *  This file is part of the Jikes RVM project (http://jikesrvm.org).
 *
 *  This file is licensed to You under the Eclipse Public License (EPL);
 *  You may not use this file except in compliance with the License. You
 *  may obtain a copy of the License at
 *
 *      http://www.opensource.org/licenses/eclipse-1.0.php
 *
 *  See the COPYRIGHT.txt file distributed with this work for information
 *  regarding copyright ownership.
 */
 
 /*
 * test setting and retrieving from object fields
 */
void main() {
  object a = alloc(2,2);
  object b = alloc(0,0);
  object c = alloc(0,0);
  a.int[0] = 1;
  a.int[1] = 2;
  a.object[0] = b;
  a.object[1] = c;

  check(a.int[0],1);
  check(a.int[1],2);
  check_obj(a.object[0],b);
  check_obj(a.object[1],c);
}

void check(int actual, int expected) {
  if (actual == expected) {
    print("OK");
  } else {
    print("ERROR");
  }
}

void check_obj(object actual, object expected) {
  if (actual == expected) {
    print("OK");
  } else {
    print("ERROR");
  }
}
