/*
 *  This file is part of the Jikes RVM project (http://jikesrvm.org).
 *
 *  This file is licensed to You under the Eclipse Public License (EPL);
 *  You may not use this file except in compliance with the License. You
 *  may obtain a copy of the License at
 *
 *      http://www.opensource.org/licenses/eclipse-1.0.php
 *
 *  See the COPYRIGHT.txt file distributed with this work for information
 *  regarding copyright ownership.
 */
void main() {
  object a = alloc(1,1);

  print("a.int[0] = ",a.int[0]," (0)",a.int[0] == 0);
  a.int[0] = 1;
  print("a.int[0] = ",a.int[0]," (1)",a.int[0] == 1);

  object b = alloc(0,0);
  print("a.object[0] = ",a.object[0]," (0)",a.object[0] == null);
  a.object[0] = b;
  print("a.object[0] = ",a.object[0]," (b)",a.object[0] == b);
}
