/*
 *  This file is part of the Jikes RVM project (http://jikesrvm.org).
 *
 *  This file is licensed to You under the Eclipse Public License (EPL);
 *  You may not use this file except in compliance with the License. You
 *  may obtain a copy of the License at
 *
 *      http://www.opensource.org/licenses/eclipse-1.0.php
 *
 *  See the COPYRIGHT.txt file distributed with this work for information
 *  regarding copyright ownership.
 */
void main() {
  print(test_method(1,0==1,"hello",alloc(0,0)));
}

/*
 * Intrinsics
 */
string test_method(int i, boolean b, string s, object o)
  intrinsic class "org.mmtk.harness.lang.ast.IntrinsicMethod"
            method "testMethod"
            signature ("int","boolean","String","org.mmtk.harness.lang.ast.ObjectValue");

