/*
 *  This file is part of the Jikes RVM project (http://jikesrvm.org).
 *
 *  This file is licensed to You under the Eclipse Public License (EPL);
 *  You may not use this file except in compliance with the License. You
 *  may obtain a copy of the License at
 *
 *      http://www.opensource.org/licenses/eclipse-1.0.php
 *
 *  See the COPYRIGHT.txt file distributed with this work for information
 *  regarding copyright ownership.
 */
type t1 {
	int intField;
	t1 objField;
}

void main() {
	t1 v1 = alloc(1,1);
	v1.intField = 2;
	v1.objField = alloc(t1);
	int result = v1.intField;
	print (result);
}