/*
 * This file is part of the Jikes RVM project (http://jikesrvm.sourceforge.net).
 * The Jikes RVM project is distributed under the Common Public License (CPL).
 * A copy of the license is included in the distribution, and is also
 * available at http://www.opensource.org/licenses/cpl1.0.php
 *
 * (C) Copyright IBM Corp. 2002
 * $Id$
 */

/* Test the JavaVM and GetEnv JNI functionality 
 * Implement native methods from GetEnv.java 
 * 
 * @author Julian Dolby
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GetEnv */

#ifndef _Included_GetEnv
#define _Included_GetEnv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GetEnv
 * Method:    nativeCall
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GetEnv_nativeCall
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
