/*
 * (C) Copyright IBM Corp. 2002
 * $Id$
 */

/* Test the JavaVM and GetEnv JNI functionality 
 * Implement native methods from GetEnv.java 
 * 
 * @author Julian Dolby
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GetEnv */

#ifndef _Included_GetEnv
#define _Included_GetEnv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GetEnv
 * Method:    nativeCall
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GetEnv_nativeCall
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
