File=Soubor
Print=Tisk
Exit=Konec
View=Zobrazit
First page=První strana
Previous page=Předchozí strana
Next page=Další strana
Last page=Poslední strana
Zoom=Lupa
Default zoom=Standardní lupa
Help=Nápověda
Index=Rejstřík
Introduction=Představení
About=O aplikaci
Page=Strana
of=z
Preview=Náhled
Init parser=Inicializuji parser
Init mappings=Inicializuji mapování 
Build FO tree=Vytvářím strom FO
Layout FO tree=Formátuji strom FO
Render=Generuji
Close=Zavřít
Go to Page=Jdi na stranu
Reload=Obnovit
Page number=Strana číslo
Cancel=Zrušit
Details=Detaily
Show=Zobrazení
