#!/bin/sh
# This is a silly script to test XSLTMark at watson
# This file is part of Jikes RVM (http://jikesrvm.sourceforge.net).
# The Jikes RVM project is distributed under the Common Public License (CPL).
# A copy of the license is included in the distribution, and is also
# available at http://www.opensource.org/licenses/cpl1.0.php
#
# (C) Copyright IBM Corp. 2002
#
# $Id$
# @author Stephen Fink

CONTRIB=/homes/meriadoc/jalapeno/contrib/benchmarks

ARGS=XalanJDriver
CLASSPATH=$CONTRIB/xalan-j_2_5_1/bin/xalan.jar
CLASSPATH=$CONTRIB/xalan-j_2_5_1/bin/xml-apis.jar:$CLASSPATH
CLASSPATH=$CONTRIB/xalan-j_2_5_1/bin/xercesImpl.jar:$CLASSPATH
CLASSPATH=$CONTRIB/XSLTMark-2.1.0/xsltmark/src/xsltmark.jar:$CLASSPATH
CLASSPATH=$CONTRIB/XSLTMark-2.1.0/xsltmark/src/xmdrivers.jar:$CLASSPATH
CLASSPATH=$CONTRIB/XSLTMark-2.1.0/xsltmark:$CLASSPATH
export CLASSPATH

PATH=./src:$PATH
export PATH

[ -d testcases ] && make -s -C testcases clean
#cd $CONTRIB/XSLTMark-2.1.0/xsltmark && /opt/IBMJava2-13/bin/java -cp $CLASSPATH com.datapower.xsltmark.XSLTMark $ARGS
cd $CONTRIB/XSLTMark-2.1.0/xsltmark && rvm -Xmx300M -cp $CLASSPATH com.datapower.xsltmark.XSLTMark $ARGS
