/*
 *  This file is part of the Jikes RVM project (http://jikesrvm.org).
 *
 *  This file is licensed to You under the Eclipse Public License (EPL);
 *  You may not use this file except in compliance with the License. You
 *  may obtain a copy of the License at
 *
 *      http://www.opensource.org/licenses/eclipse-1.0.php
 *
 *  See the COPYRIGHT.txt file distributed with this work for information
 *  regarding copyright ownership.
 */
/* Test the JavaVM and GetEnv JNI functionality
 * Implement native methods from GetEnv.java
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GetEnv */

#ifndef _Included_GetEnv
#define _Included_GetEnv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GetEnv
 * Method:    nativeCall
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GetEnv_nativeCall
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
