#! /bin/bash

export RVM_HOME="`dirname "$0"`"

export BASE_ARGS="-X:ic=$RVM_HOME/RVM.code.image -X:id=$RVM_HOME/RVM.data.image -X:ir=$RVM_HOME/RVM.rmap.image -X:vmClasses=$RVM_HOME/jksvm.jar:$RVM_HOME/rvmrt.jar -Duser.timezone=$(date +%Z) -Djava.home=$RVM_HOME -Dgnu.classpath.home.url=file:$RVM_HOME -Dgnu.classpath.vm.shortname=JikesRVM -Duser.home=$HOME -Duser.dir=`pwd` -Duser.name=`whoami` -Dos.name=`uname -s` -Dos.version=`uname -r` -Dos.arch=`uname -m`"

# This may need to be LIBPATH under AIX or SHLIB_PATH on HP-UX
export LD_LIBRARY_PATH=$RVM_HOME:$LD_LIBRARY_PATH

if (( $# == 0 )) || ((( $# >= 1 )) && [[ $1 != -gdb ]] ); then
@PRELOAD@ exec "$RVM_HOME/JikesRVM" $BASE_ARGS "$@"
else
# Remove -gdb arg
shift

export GDB_ARGS=
if (( $# >= 1 )) && [[ $1 == -fullname ]]; then
    GDB_ARGS="$1";
    shift
fi

export TMP_GDB_COMMANDS=$RVM_HOME/gdb.commandlineArgs

echo -n "set args" > $TMP_GDB_COMMANDS
echo $BASE_ARGS | tr ' ' '\n' | awk '{print "\"" $1 "\"" }' | tr '\n' ' ' >> $TMP_GDB_COMMANDS
#echo $* | tr ' ' '\n' | awk '{print "\"" $1 "\"" }' >> $TMP_GDB_COMMANDS
for arg in "$@"; do
    echo -n " \"$arg\"" >> $TMP_GDB_COMMANDS 
done 
echo "" >> $TMP_GDB_COMMANDS

# Tell gdb to completely ignore some signals that Jikes RVM uses
# for its own purposes.
# SIGSEGV is a null pointer exception
echo "handle SIGSEGV nostop noprint pass" >> $TMP_GDB_COMMANDS

# Set an initial breakpoint right before we start the jump into VM.boot
echo "break bootThread" >> $TMP_GDB_COMMANDS

@PRELOAD@ gdb "${gdb_args[@]}" "$RVM_HOME/JikesRVM" "--command=$TMP_GDB_COMMANDS" 
fi
