#! /bin/bash

export RVM_DIR="`dirname "$0"`"
export RVM_HOME="`dirname "$0"`"

export BASE_ARGS="-X:ic=$RVM_DIR/RVM.code.image -X:id=$RVM_DIR/RVM.data.image -X:ir=$RVM_DIR/RVM.rmap.image -X:vmClasses=$RVM_DIR/jksvm.jar:$RVM_DIR/rvmrt.jar -Duser.timezone=$(date +%Z) -Drvm.root=$RVM_HOME -Drvm.build=$RVM_DIR -Djava.home=$RVM_HOME -Dgnu.classpath.home.url=file:$RVM_DIR -Dgnu.classpath.vm.shortname=JikesRVM -Duser.home=$HOME -Duser.dir=`pwd` -Duser.name=`whoami` -Dos.name=`uname -s` -Dos.version=`uname -r` -Dos.arch=`uname -m`"

# This may need to be LIBPATH under AIX or SHLIB_PATH on HP-UX
export LD_LIBRARY_PATH=$RVM_DIR:$LD_LIBRARY_PATH

@PRELOAD@ exec "$RVM_DIR/JikesRVM" $BASE_ARGS "$@"
