#!/bin/sh
# This is a silly script to test XSLTMark at watson

CONTRIB=/homes/meriadoc/jalapeno/contrib/benchmarks

ARGS=XalanJDriver
CLASSPATH=$CONTRIB/xalan-j_2_4_D1/bin/xalan.jar
CLASSPATH=$CONTRIB/xalan-j_2_4_D1/bin/xml-apis.jar:$CLASSPATH
CLASSPATH=$CONTRIB/xalan-j_2_4_D1/bin/xercesImpl.jar:$CLASSPATH
CLASSPATH=$CONTRIB/XSLTMark-2.1.0/xsltmark/src/xsltmark.jar:$CLASSPATH
CLASSPATH=$CONTRIB/XSLTMark-2.1.0/xsltmark/src/xmdrivers.jar:$CLASSPATH
CLASSPATH=$CONTRIB/XSLTMark-2.1.0/xsltmark:$CLASSPATH
export CLASSPATH

PATH=./src:$PATH
export PATH

[ -d testcases ] && make -s -C testcases clean
#cd $CONTRIB/XSLTMark-2.1.0/xsltmark && java com.datapower.xsltmark.XSLTMark $ARGS
echo $CLASSPATH
cd $CONTRIB/XSLTMark-2.1.0/xsltmark && rvm -cp $CLASSPATH com.datapower.xsltmark.XSLTMark $ARGS
