#!/bin/ksh
#
# (C) Copyright IBM Corp. 2001
#
#
# This file defines a set of environment variables needed to build and
# run Jikes RVM.  This file is sourced by the installation scripts; you
# do not need to source this file into your command-prompt shell.
#
# IMPORTANT: You need to modify this file to reflect your environment!
#

#########
# PART I: Preprocessor directives that hold for every config on this target
#########
# target architecutre is IA32
export RVM_FOR_IA32=1

# target OS is Linux
export RVM_FOR_LINUX=1

# Default to 1, since having a hardware SMP running a 2.4 kernal 
# with the appropriate pthread library is currently somewhat unusual.
# NOTE: the key requirement for setting this to 0 (ie having SMP support)
#       is that you have a 2.4 kernel and that glibc is compiled 
#       to use the GS segment register to access pthread-local storage.  
#       See discussion in rvm-researchers archive and the userguide FAQ.
export RVM_FOR_SINGLE_VIRTUAL_PROCESSOR=1

##########
# PART II: Where to find tools and resources on this target
########## 

export HOST_JAVA_HOME="/opt/IBMJava2-13"

# the JDK java executable
export HOST_JAVA="/opt/IBMJava2-13/jre/bin/java"
#

# the JDK javadoc executable
export HOST_JAVADOC="/opt/IBMJava2-13/bin/javadoc"

# the JDK jar executable
export HOST_JAR="/opt/IBMJava2-13/bin/jar"

# the JDK javac executable
export HOST_JAVAC="/opt/IBMJava2-13/bin/javac"

# the JDK standard library jar files
export HOST_REPOSITORIES="/opt/IBMJava2-13/jre/lib/rt.jar"

# the JDK tools jar
export HOST_TOOLS="/opt/IBMJava2-13/lib/tools.jar"

# path for GNU make
export GNU_MAKE="/usr/bin/make"

# path for jikes.
export JIKES=/usr/bin/jikes

# what C compilers should be used?
export CC='/usr/bin/gcc -w -O'

# what C++ compilers should be used?
export CPLUS='/usr/bin/g++ -g'

# how to link a shared C++ library
export LDSHARED="/usr/bin/g++ -shared"

#
export JNI_NATIVE_LIBS_LD="ld -bnoentry -bM:SRE -lc_r -blibpath:/usr/lib/threads:/usr/lib:/lib -bE:"

# The configuration for building the user guide.
# You may have to edit this file.
export USER_GUIDE_CONFIG="${RVM_ROOT}/rvm/doc/userguide/config.mk"


#  some Unix commands
export AWK=/bin/awk
export BASH="/bin/bash"
export DIFF=/usr/bin/diff
export FGREP=/bin/fgrep
export FIND=/bin/find
export GNU_TAR=/bin/tar
export GREP=/bin/grep
export MD5SUM=/usr/bin/md5sum
export PS=/bin/ps
export SED=/usr/bin/sed
export WGET=/usr/bin/wget
export XARGS="/usr/bin/xargs"
export UNZIP="/usr/bin/unzip"
