#!/bin/ksh
#
# (C) Copyright IBM Corp. 2001
#
#
# This file defines a set of environment variables needed to build and
# run Jikes RVM.  This file is sourced by the installation scripts; you
# do not need to source this file into your command-prompt shell.
#
# IMPORTANT: You need to modify this file to reflect your environment!
#

# NOTE: Assumes 'mount c:/Program\ Files/IBM /IBM'
export HOST_JAVA_HOME="/IBM/Java13"

# the JDK java executable
export HOST_JAVA="/IBM/Java13/jre/bin/java"

# the JDK javadoc executable
export HOST_JAVADOC="/IBM/Java13/jre/bin/javadoc"

# the JDK javac executable
export HOST_JAVAC="/usr/local/bin/jikes"

# the JDK jar executable
export HOST_JAR="/IBM/Java13/bin/jar"

# the JDK standard library jar files
export HOST_REPOSITORIES="/IBM/Java13/jre/lib/rt.jar"

# the JDK tools jar
export HOST_TOOLS="/IBM/Java13/jre/lib/tools.jar"

# path for GNU make
export GNU_MAKE="/usr/bin/make"

# path for jikes.
export JIKES="/usr/local/bin/jikes"

# what C compilers should be used?
export CC='/usr/bin/gcc -w -O'
 
# what C++ compilers should be used?
export CPLUS='/usr/bin/g++ -g'   

# how to link a shared C++ library
export LDSHARED="/usr/bin/g++ -shared"

#
export JNI_NATIVE_LIBS_LD="ld -bnoentry -bM:SRE -lc_r -blibpath:/usr/lib/threads:/usr/lib:/lib -bE:"


# The configuration for building the user guide.
# You may have to edit this file.
export USER_GUIDE_CONFIG="${RVM_ROOT}/rvm/doc/userguide/config.mk"


#  some Unix commands
export AWK=/bin/awk
export BASH=/usr/bin/bash
export DIFF=/usr/bin/diff
export FGREP=/bin/fgrep
export FIND=/bin/find
export GNU_TAR=/bin/tar
export GREP=/bin/grep
export MD5SUM=/usr/bin/md5sum
export PS=/bin/ps
export SED=/usr/bin/sed
export WGET=/usr/bin/wget
export DIFF="/usr/bin/diff"
export MD5SUM=/usr/bin/md5sum
export GNU_TAR=/bin/tar
export XARGS="/usr/bin/xargs"
