#!/bin/ksh
#
# (C) Copyright IBM Corp. 2001
#
#
# This file defines a set of environment variables needed to build and
# run Jikes RVM.  This file is sourced by the installation scripts; you
# do not need to source this file into your command-prompt shell.
#
# IMPORTANT: You need to modify this file to reflect your environment!
#

#########
# PART I: Preprocessor directives that hold for every config on this target
#########
# target architecutre is PowerPC
export RVM_FOR_POWERPC=1

# target OS is Linux
export RVM_FOR_LINUX=1

# SMP is not supported on PowerPC/Linux.
# pthread library doesn't play nicely with RVM since it wants to
# mask the bottom bits of stackpointer to find phtread local storage.
export RVM_FOR_SINGLE_VIRTUAL_PROCESSOR=1

##########
# PART II: Where to find tools and resources on this target
########## 

export HOST_JAVA_HOME=/usr/local/jre13

# the JDK java executable
export HOST_JAVA="$HOST_JAVA_HOME/bin/java"

# the JDK javadoc executable
export HOST_JAVADOC="$HOST_JAVA_HOME/bin/javadoc"

# the JDK javac executable
export HOST_JAVAC="$HOST_JAVA_HOME/bin/javac"

# the JDK jar executable
export HOST_JAR="$HOST_JAVA_HOME/bin/jar"

# the JDK standard library jar files
export HOST_REPOSITORIES="$HOST_JAVA_HOME/lib/rt.jar"

# the JDK tools jar
export HOST_TOOLS="$HOST_JAVA_HOME/lib/tools.jar"

# path for GNU make
export GNU_MAKE=/usr/bin/make

# path for jikes.
export JIKES=/usr/bin/jikes

# what C compilers should be used?
export CC="/usr/bin/gcc -w -O -Wa,-mppc"

# what C++ compilers should be used?
export CPLUS="/usr/bin/g++"

# how to link a shared C++ library
export LDSHARED="/usr/bin/g++ -shared"

# used by the jbuild.linkBooter
export CPP=/usr/bin/cpp

#
export JNI_NATIVE_LIBS_LD="ld -bnoentry -bM:SRE -lc_r -blibpath:/usr/lib/threads:/usr/lib:/lib -bE:"

# The configuration for building the user guide.
# You may have to edit this file.
export USER_GUIDE_CONFIG="${RVM_ROOT}/rvm/doc/userguide/config.mk"


export AWK="/usr/bin/awk"
export BASH="/bin/bash"
export DIFF=/usr/bin/diff
export FGREP="/usr/bin/fgrep"
export FIND="/usr/bin/find"
export GNU_TAR="/usr/bin/tar"
export GREP="/usr/bin/grep"
export MD5SUM=md5sum
export PS=/bin/ps
export SED=/usr/bin/sed
export WGET=wget
export XARGS="/usr/bin/xargs"
