#!/bin/csh
#
# (C) Copyright IBM Corp. 2002
#
# $Id$
#
# Copies the build trace files in the subdirectories on $1 into 
#   a newly created $2/images directory
#
# Assumptions: $1 and $2 are existing directories
#
# @author: Michael Hind
#

set source = $1
set dest = $2/images
mkdir $dest

cd $source
foreach i (*)
  mkdir $dest/$i  
  cp $i/RVM.trace $dest/$i
end


