#!/bin/csh
#
# This file is part of Jikes RVM (http://jikesrvm.sourceforge.net).
# The Jikes RVM project is distributed under the Common Public License (CPL).
# A copy of the license is included in the distribution, and is also
# available at http://www.opensource.org/licenses/cpl1.0.php
#
# (C) Copyright IBM Corp. 2002
#
#
# Copies the build trace files in the subdirectories on $1 into 
#   a newly created $2/images directory
#
# Assumptions: $1 and $2 are existing directories
#
# @author: Michael Hind
#

set source = $1
set dest = $2/images
mkdir $dest

cd $source
foreach i (*)
  mkdir $dest/$i  
  cp $i/RVM.trace $dest/$i
end


