/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_JikesRVM_VM_0005fProcess */

#ifndef _Included_com_ibm_JikesRVM_VM_0005fProcess
#define _Included_com_ibm_JikesRVM_VM_0005fProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibm_JikesRVM_VM_0005fProcess
 * Method:    exec4
 * Signature: (Ljava/lang/String;[Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_ibm_JikesRVM_VM_1Process_exec4
  (JNIEnv *, jobject, jstring, jobjectArray, jobjectArray, jstring);

/*
 * Class:     com_ibm_JikesRVM_VM_0005fProcess
 * Method:    destroyInternal
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_ibm_JikesRVM_VM_1Process_destroyInternal
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
