/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_net_InetAddressJpn */

#ifndef _Included_java_net_InetAddressJpn
#define _Included_java_net_InetAddressJpn
#ifdef __cplusplus
extern "C" {
#endif
#undef java_net_InetAddressJpn_MAX_HOSTNAME
#define java_net_InetAddressJpn_MAX_HOSTNAME 256L
#undef java_net_InetAddressJpn_trace
#define java_net_InetAddressJpn_trace 0L
/*
 * Class:     java_net_InetAddressJpn
 * Method:    getAliasesByNameImpl
 * Signature: (Ljava/lang/String;)[Ljava/net/InetAddress;
 */
JNIEXPORT jobjectArray JNICALL Java_java_net_InetAddressJpn_getAliasesByNameImpl
  (JNIEnv *, jclass, jstring);

/*
 * Class:     java_net_InetAddressJpn
 * Method:    getHostByAddrImpl
 * Signature: (I)Ljava/net/InetAddress;
 */
JNIEXPORT jobject JNICALL Java_java_net_InetAddressJpn_getHostByAddrImpl
  (JNIEnv *, jclass, jint);

/*
 * Class:     java_net_InetAddressJpn
 * Method:    getHostNameImpl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_java_net_InetAddressJpn_getHostNameImpl
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
