#
# (C) Copyright IBM Corp. 2001
#
#$Id$
#
# @author unascribed
#
include			$(JAL_BUILD)/Make.rules

$(DEST):		VM_0005fInetAddress.C VM_0005fInetAddress.h
	$(LDSHARED) -o $(DEST) -I$(JAL_ROOT)/rvm/src/include -O -g $<
