#
# (C) Copyright IBM Corp. 2001
#
# $Id$
#
# @author David Hovemeyer
#
include			$(JAL_BUILD)/Make.rules

$(DEST):		syswrap.C syswrap.h
	$(LDSHARED) -o $(DEST) $(CXXFLAGS) -I$(JAL_ROOT)/rvm/src/include -I$(JAL_BUILD)/RVM.scratch -O -g $<
