#! /bin/bash

# This file is part of the Jikes RVM project (http://jikesrvm.sourceforge.net).
# The Jikes RVM project is distributed under the Common Public License (CPL).
# A copy of the license is included in the distribution, and is also
# available at http://www.opensource.org/licenses/cpl1.0.php
#
# (C) Copyright IBM Corp. 2002
# $Id$
# @author David Hovemeyer
#
# Search for jar files that appear to contain a given class

className=$1
if [ -z "$className" ]; then
    echo "Usage: findClass <class name>"
    exit 1
fi

for j in `find . -name '*.jar' -print`; do
    count=`jar tf $j | grep $className | wc -l`
    if [ $count -gt 0 ]; then
	echo $j
    fi
done
