#! /usr/bin/perl

# This file is part of the Jikes RVM project (http://jikesrvm.sourceforge.net).
# The Jikes RVM project is distributed under the Common Public License (CPL).
# A copy of the license is included in the distribution, and is also
# available at http://www.opensource.org/licenses/cpl1.0.php
#
# (C) Copyright IBM Corp. 2002
# @author David Hovemeyer
# $Id$

# Read files from stdin, and combine them into a path
# string that can be used as a classpath.

my $BASEDIR = shift @ARGV;
(defined $BASEDIR) || die;

my $cp;
while (<>) {
    chop;
    s,^\./,,;
    $cp = "$BASEDIR/$_:$cp";
}

chop $cp;
print "$cp\n";
