#
# (C) Copyright IBM Corp. 2002
#
#$Id$
#
# @author David Grove

COMMON_DIR = $(RVM_ROOT)/rvm/src/vm/compilers/optimizing/ir/conversions/lir2mir

RULE_FILES = 	$(MIR_LIR2MIR_DIR)/PPC_Common.rules \
		$(MIR_LIR2MIR_DIR)/PPC_Alu32.rules \
		$(MIR_LIR2MIR_DIR)/PPC_Mem32.rules 

