#
# (C) Copyright IBM Corp. 2002
#
#$Id$
#
# @author David Grove

COMMON_DIR = $(RVM_ROOT)/rvm/src/vm/compilers/optimizing/ir/conversions/lir2mir

RULE_FILES = 	$(COMMON_DIR)/NonTerminals.rules \
		$(MIR_LIR2MIR_DIR)/PPC32.rules 
