#
# This file is part of the Jikes RVM project (http://jikesrvm.sourceforge.net).
# The Jikes RVM project is distributed under the Common Public License (CPL).
# A copy of the license is included in the distribution, and is also
# available at http://www.opensource.org/licenses/cpl1.0.php
#
# (C) Copyright IBM Corp. 2002
#
#$Id$
#
# @author David Grove

COMMON_DIR = $(RVM_ROOT)/rvm/src/vm/compilers/optimizing/ir/conversions/lir2mir
#
RULE_FILES = $(MIR_LIR2MIR_DIR)/IA32.rules 
