#!/bin/ksh
#
# (C) Copyright IBM Corp. 2001
#
# $Id$
#
# @author Julian Dolby

# This script will build the boot images
# It then signals another script, night-sanity-run to perform the runs.

export PATH=$PATH:.

# Where the fullshadow and other verbose output are placed, not mailed
export VERBOSE_LOG=$RVM_ROOT/results/verbose.log

# Where the build output is placed, this is mailed when the tests failed
export BUILD_LOG=$RVM_ROOT/results/build.log

umask 022

# build the boot images, but don't run any tests
echo "Building the boot images\n" >> $BUILD_LOG

$RVM_ROOT/rvm/regression/NightSanityDriver -common "-images $RVM_ROOT/images -result $RVM_ROOT/results -norun -wait sem" -config $1 >> $BUILD_LOG 2>> $BUILD_LOG

# build javadoc for FullAdaptiveSemispace image.
. $RVM_ROOT/images/FullAdaptiveSemiSpace/jbuild.environment
$RVM_ROOT/rvm/bin/jdoc.sh $RVM_ROOT/doc/api both >> $BUILD_LOG 2>> $BUILD_LOG

echo "\n\nBuild complete, builder script exiting.\n" >> $BUILD_LOG



