#!/bin/ksh
#
# (C) Copyright IBM Corp. 2001
#
# $Id$
#
# @author Julian Dolby

# This script will run sanity and performance tests.  
# It assumes the boot images have 
# already been built.  (See night-sanity-build.)
# The output of this script is the results from the sanity test
# (The results of the fullshadow are stored in the file defined in
#  the VERBOSE_LOG variable.)

# How often to look to see if the builds are done
SLEEP_DURATION="120"

export JALAPENO_HOME=/homes/fury5/jalapeno

export PATH=/usr/gnu/bin:$JALAPENO_HOME/bin:$RVM_ROOT/bin:$PATH:/usr/contrib/bin:.

# the resulting message
MSG=$RVM_ROOT/MSG

# The directory where the archive lives
export ARCHIVE=~/archive

mkdir -p $RVM_ROOT/results

# Where the fullshadow and other verbose output are placed, not mailed
export VERBOSE_LOG=$RVM_ROOT/results/verbose.log

# Where the build output is placed, this is mailed when the tests failed
export BUILD_LOG=$RVM_ROOT/results/build.log

# Where the run output is placed, this is mailed when the tests failed
export RUN_LOG=$RVM_ROOT/results/run.log

# Where the performance results are placed
export PERF_LOG=$RVM_ROOT/results/performance.log

umask 022

# Determine architecture and set number of processors accordingly
ARCH=`uname`
if [[ $ARCH = 'Linux' ]] then
  NUM_PROCS=4
else
  NUM_PROCS=2
fi

echo "\n\nRunning the sanity tests\n" >> $RUN_LOG

#This shouldn't be needed, but just in case
chmod 755 $RUN_LOG

# cd to the SHADOW to get things started
cd $RVM_ROOT

# sanity runs
$RVM_ROOT/rvm/regression/NightSanityDriver -common "-images $RVM_ROOT/images -result $RVM_ROOT/results/sanity -nobuild -numprocs $NUM_PROCS -wait sem" -config $1 >> $RUN_LOG 2>> $RUN_LOG

. $RVM_ROOT/images/FullAdaptiveSemispace/jbuild.environment

# performance runs
$RVM_ROOT/rvm/regression/NightSanityDriver -common "-images $RVM_ROOT/images -result $RVM_ROOT/results/performance -nobuild -numprocs $NUM_PROCS -wait sem -performance $PERF_LOG" -config $2 >> $RUN_LOG 2>> $RUN_LOG

# Fix the permission bits because umask doesn't seem to be working correctly
echo "fixing permission bits" >> $RUN_LOG
chmod -R 755 $RVM_ROOT 2>> $RUN_LOG

# Archive result files and performance results
echo "Archiving results into $ARCHIVE\n" >> $RUN_LOG
(cd $RVM_ROOT/results; find . -name cp -prune -o -type f -print | xargs $GNU_TAR czvf $ARCHIVE/archive.`date +"%A"`.`uname`.tar.gz) >> $VERBOSE_LOG 2>> $VERBOSE_LOG

# determine how many ran, failed, and passed, then build a summary line
numran=`grep "sane" $RUN_LOG | wc -l`
numfailed=`grep "You are NOT sane" $RUN_LOG | wc -l`
numpassed=`grep "You are sane" $RUN_LOG | wc -l`
echo "Ran $numran, Passed \t$numpassed, Failed \t$numfailed" >> $RUN_LOG

if [[ $numran -eq 0 ]] then
  echo "*** No tests were run! *** " >> $MSG
  echo "There was probably an error in building the boot images.\n\n" >> $MSG
else
#  Build the summary line
  echo "Ran \t$numran \nPassed \t$numpassed\nFailed \t$numfailed \n\n" >> $MSG
fi

# Print some details on the failures
if [[ $numfailed -gt 0 ]] then
  echo >> $MSG
  echo Failure Details >> $MSG
  echo --------------- >> $MSG
  echo >> $MSG
  fgrep "You are NOT sane" $RUN_LOG  \
    | sed -e "s/RunSanityTests://"   \
    | sed -e "s/\/.*tests\///"   \
    | sed -e "s/You are NOT sane/Failed/"   \
    >> $MSG
fi


# Removed at Mike Hind's request
# Describe where the information can be found
# echo "Further details of this run can be found in\n" >> $MSG
# echo "     run details: $RUN_LOG\n " >> $MSG
# echo "     build details: $BUILD_LOG\n " >> $MSG
# echo "     verbose details: $VERBOSE_LOG\n " >> $MSG
# echo "     performance details: $PERF_LOG" >> $MSG

# Grab the bottom line performance and place it in a more visible place
echo >> $MSG
echo >> $MSG
echo Performance Summary >> $MSG
$AWK -f $RVM_ROOT/rvm/regression/PerformanceBottomLine.awk $RVM_ROOT/results/performance.log >> $MSG

# Print verbose performance data for SPECjvm98
echo >> $MSG
echo SPECjvm98 Performance Details >> $MSG
echo ----------------------------- >> $MSG
$AWK -f $RVM_ROOT/rvm/regression/PerformanceVerbose.awk -v targetBench=SPECjvm98 $RVM_ROOT/results/performance.log >> $MSG


# Finally!  Send the mail message to those who care
# echo "mailing status to $RESULT_MAILING_LIST"
cat MSG >> $RUN_LOG

if [[ $numran -gt 0 && $numfailed -eq 0 ]] then
  cat $MSG | mail -s "[$ARCH] regression SUCCEEDED" $RESULT_MAILING_LIST 
else
  cat $MSG | mail -s "[$ARCH] regression FAILED $numfailed tests" $RESULT_MAILING_LIST
fi

#
# Check that files contain an @author tag, a CVS Id tag, and a Copyright notice.
#
export CHECK_DIR=$RVM_ROOT/results

# Check files
$RVM_ROOT/rvm/bin/findDeviantFiles $RVM_ROOT/rvm $CHECK_DIR rvm
 
# Email results 
# Only email to pfs at the moment
if [[ -s $CHECK_DIR/noAuthor.rvm ]] then
 cat $CHECK_DIR/noAuthor.rvm    | mail -s "files without an @author tag"     pfs 
else
 echo " " | mail -s "no files without an @author tag"     pfs 
fi
if [[ -s $CHECK_DIR/noId.rvm ]] then
  cat $CHECK_DIR/noId.rvm       | mail -s "files without a CVS Id tag"       pfs 
else
  echo " " | mail -s "no files without a CVS Id tag"       pfs 
fi
if [[ -s $CHECK_DIR/noCopyright.rvm ]] then
  cat $CHECK_DIR/noCopyright.rvm| mail -s "files without a Copyright notice" pfs 
else
  echo " " | mail -s "no files without a Copyright notice" pfs 
fi

# measure compilation time
export MEASURE_COMPILATION_LOG=$RVM_ROOT/results/measureCompilation.log

$RVM_ROOT/rvm/regression/NightSanityDriver -common "-images $RVM_ROOT/images -result $RVM_ROOT/results/performance -nobuild -numprocs $NUM_PROCS -wait sem -rc-args -X:measureCompiliation=true -performance $PERF_LOG" -config night-sanity-performance >> $MEASURE_COMPILATION_LOG 2>> $MEASURE_COMPILATION_LOG


