#! /bin/bash
#
# This file is part of Jikes RVM (http://jikesrvm.sourceforge.net).
# The Jikes RVM project is distributed under the Common Public License (CPL).
# A copy of the license is included in the distribution, and is also
# available at http://www.opensource.org/licenses/cpl1.0.php
#
# (C) Copyright IBM Corp. 2001, 2004
#
#
# This file defines a set of environment variables needed to build and
# run Jikes RVM.  This file is sourced by the installation scripts; you
# do not need to source this file into your command-prompt shell.
#
# This file is for AIX on 32-bit PowerPC.
#
# IMPORTANT: You need to modify this file to reflect your AIX environment!
#

#########
# PART I: Preprocessor directives that hold for every config on this target
#########
# target architecture is PowerPC
export RVM_FOR_POWERPC=1
export RVM_FOR_32_ADDR=1

# target OS is AIX
export RVM_FOR_AIX=1

# SMP support is always ok on AIX.
export RVM_FOR_SINGLE_VIRTUAL_PROCESSOR=0

export BOOTIMAGE_DATA_ADDRESS=0x30000000
export BOOTIMAGE_CODE_ADDRESS=0x34000000
export BOOTIMAGE_RMAP_ADDRESS=0x37000000
export MAXIMUM_MAPPABLE_ADDRESS=0xd0000000

# Hardware performance monitor api available in AIX5.1 (bos.pmapi)
export RVM_HPM_DIR="/usr/pmapi"
export RVM_WITH_HPM=1

##########
# PART II: Where to find tools and resources on this target
#
# The configuration process can make use of auto-guessing features in
# the RVM_ROOT/bin/jconfigure program.  You can see the results of
# its guesses in "RVM_BUILD/environment.host".  (This particular file
# doesn't use those features, though, since they won't work if
# you're doing a cross-build.)
########## 

# Selection of GNU Classpath version is platform independent and fairly
# involved; therefore it has been factored out into a separate file.
. $RVM_ROOT/config/classpath-version

# Set HOST_VM_TYPE to reflect the JVM the Jikes RVM will be built upon.
[[ ${HOST_VM_TYPE-} ]] || HOST_VM_TYPE=IBM-50

# Root of JDK installation.
[[ ${HOST_JAVA_HOME-} ]] || HOST_JAVA_HOME="/usr/java15"

# Path for GNU make
export GNU_MAKE="/usr/gnu/bin/make"

## What C compiler should be used?  We only use the GNU C compiler
## on the project, although it is possible that other compilers might work.
##
export CC="/usr/gnu/bin/gcc -w -O -Wa,-mppc"

## What C++ compiler should be used?
export CPLUS="/usr/gnu/bin/g++ -w -O -Wa,-mppc"

# how to link a shared C++ library (possibly also recompile one 
# or more source files in it)
export LDSHARED="/usr/gnu/bin/g++ -shared"

# The configuration for building the user guide.
# You may have to edit this file.
export USER_GUIDE_CONFIG="${RVM_ROOT}/doc/userguide/config.mk"

# some Unix commands used in sanity rules and automatic rvmrt retrieval
export AWK="/usr/gnu/bin/gawk"
export BASH="/usr/gnu/bin/bash"
# You need one of Yacc or Bison (one will usually be installed)
# If you're using Bison, uncomment the line below:
# BISON="bison"
export CVS="/usr/bin/cvs"
export DIFF="/usr/gnu/bin/diff"
export FGREP="/usr/gnu/bin/fgrep"
export FIND="/usr/gnu/bin/find"
export GNU_TAR="/usr/gnu/bin/tar"
export GREP="/usr/gnu/bin/grep"
export MD5SUM="/usr/gnu/bin/md5sum"
export PS="/usr/bin/ps"
export SED="/usr/gnu/bin/sed"
export XARGS="/usr/gnu/bin/xargs"

export ZIP_CMD="/usr/bin/zip"
export UNZIP_CMD="/usr/bin/unzip"

##########
# PART III: Additional variables for running Eclipse on Jikes RVM
########## 

## Uncomment this and set it to the directory created when you extracted
## eclipse-SDK-3.0.1-aix-motif.zip

## (Eclipse extracts itself into a directory named "eclipse",
##  without a version number.)
# export ECLIPSE_INSTALL_DIR="$HOME/Eclipse-3.0/eclipse"

## To run Eclipse on Jikes RVM, you will need to use the Xalan XML parser.
## Setting up to use Xalan may also help you run other programs
## under Jikes RVM.
##
## We tested using XALAN 2.6.0; visit http://xml.apache.org/xalan-j/
## and download the "Xalan Java binary distribution", since that
## distribution has Xerces packaged with it.  The file is
## xalan-j_2_6_0-bin.tar.gz.

## Unlike how we treat the Classpath .jar file and .so files, we don't
## copy Xalan into $RVM_BUILD.  (We could easily modify the build system to do
## so, though.)
# export XALAN_J_DIR="/usr/local/xalan-j_2_6_0"

##########
# PART IV: Miscellaneous variables.
#
# If you add any variables to this section, please document them.  Please.
##########

# BENCHMARK_ROOT is used in running some of the Jikes RVM regression
# tests.  It doesn't need to be set unless you are running those tests.
export BENCHMARK_ROOT=""
