#! /bin/bash
#
#  This file is part of the Jikes RVM project (http://jikesrvm.org).
#
#  This file is licensed to You under the Common Public License (CPL);
#  You may not use this file except in compliance with the License. You
#  may obtain a copy of the License at
#
#      http://www.opensource.org/licenses/cpl1.0.php
#
#  See the COPYRIGHT.txt file distributed with this work for information
#  regarding copyright ownership.
#

#
# This script will be the images needed by the Run-gather-dna script
#   Arguments:  directory to hold image directories
#                  ex BuildImages /u/hind/RVMSanityTests
#
# @author Michael Hind, Dec 1, 2001
#

# parent of build directories is command line argument to the script

if [[ $RVM_ROOT = "" ]]; then
   echo "\n***$0: please set your RVM_ROOT environment variable (eg. $HOME/jvmShadow)***\n"
   exit 1
fi

BUILDDIR=$1

IMAGES='FastBaseAdaptiveGenMS FastOpt0GenMS FastOpt1GenMS FastAdaptiveGenMS'

for image in $IMAGES
do
   rm -rf $BUILDDIR/$image
   export RBUILD=$BUILDDIR/$image
   echo "Configuring $image"
   $RVM_ROOT/bin/jconfigure $image
   cd $BUILDDIR/$image
   echo "Building $image"
   ./jbuild >RVM.trace 2>&1
done
