#! /bin/bash
#
#  This file is part of the Jikes RVM project (http://jikesrvm.org).
#
#  This file is licensed to You under the Common Public License (CPL);
#  You may not use this file except in compliance with the License. You
#  may obtain a copy of the License at
#
#      http://www.opensource.org/licenses/cpl1.0.php
#
#  See the COPYRIGHT.txt file distributed with this work for information
#  regarding copyright ownership.
#

# This script will run the system on the SPECjvm98 benchmarks,
# and collect profile data, dumped to a file.
#
# usage: GenerateSPECjvmProfile <profile Data file> <build directory>
#
# @author Stephen Fink
# @modified Peter F. Sweeney 8/13/2003 additional argument where to find image

FILE=$1
BUILDDIR=$2

if [[ $RROOT = "" ]]; then
   echo "\n***$0: please set your RROOT environment variable (eg. $HOME/jvmShadow)***\n"
   exit 1
fi

$RROOT/bin/RunSanityTests -measureCompilation -configuration FastBaseAdaptiveGenMS -images $BUILDDIR -test SPECjvm98 -nobuild -rc-args "-X:aos:final_report_level=2 -X:aos:enable_recompilation=false -X:aos:initial_compiler=base -X:base:edge_counter_file=$FILE"
