/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class energy_Scaler */

#ifndef _Included_energy_Scaler
#define _Included_energy_Scaler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     energy_Scaler
 * Method:    scale
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_energy_Scaler_scale
  (JNIEnv *, jclass, jint);

/*
 * Class:     energy_Scaler
 * Method:    freqAvailable
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_energy_Scaler_freqAvailable
  (JNIEnv *, jclass);

/*
 * Class:     energy_Scaler
 * Method:    SetGovernor
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_energy_Scaler_SetGovernor
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
