#! /bin/bash

# (C) Copyright IBM Corp. 2002
# $Id$

# Search for jar files that appear to contain a given class

className=$1
if [ -z "$className" ]; then
    echo "Usage: findClass <class name>"
    exit 1
fi

for j in `find . -name '*.jar' -print`; do
    count=`jar tf $j | grep $className | wc -l`
    if [ $count -gt 0 ]; then
	echo $j
    fi
done
