# -*- coding: iso-8859-1 ; mode: Makefile ;-*-
#
# Copyright © IBM Corp. 2003
#
# $Id$
#
# Substitute a brief description of what this Makefile does.
#
# @author Your Name Here
# @date 11 October 2003

## The stuff below will not be useful in every case.
ifdef RVM_BUILD
  JAL_BUILD ?= ${RVM_BUILD}
endif

ifdef INCLUDED_MAKEFILE
  include ${INCLUDED_MAKEFILE}
else
  ifneq ($JAL_BUILD,"")
    include			$(JAL_BUILD)/Make.rules.target
  endif
endif

