/*
 *  This file is part of the Jikes RVM project (http://jikesrvm.org).
 *
 *  This file is licensed to You under the Eclipse Public License (EPL);
 *  You may not use this file except in compliance with the License. You
 *  may obtain a copy of the License at
 *
 *      http://www.opensource.org/licenses/eclipse-1.0.php
 *
 *  See the COPYRIGHT.txt file distributed with this work for information
 *  regarding copyright ownership.
 */

option verbose "3";

/**
 * This is a simple test that creates lots of cyclic garbage.
 */
void main() {
  int cycleSize = 1000;

  while (gcCount() < 25) {
    createCycle(cycleSize);
  }
}

object createCycle(int size) {
  object head = alloc(1, 10);
  object tail = head;
  while(size > 0) {
    tail.object[0] = alloc(1, 10);
    tail = tail.object[0];
    size = size - 1;
  }
  tail.object[0] = head;
  return head;
}
