/*
 *  This file is part of the Jikes RVM project (http://jikesrvm.org).
 *
 *  This file is licensed to You under the Common Public License (CPL);
 *  You may not use this file except in compliance with the License. You
 *  may obtain a copy of the License at
 *
 *      http://www.opensource.org/licenses/cpl1.0.php
 *
 *  See the COPYRIGHT.txt file distributed with this work for information
 *  regarding copyright ownership.
 */

/*
 * MMTk script that mimics the behaviour of the FixedLive benchmark
 */
type tree {
  int i1;
  int i2;
  tree left;
  tree right;
}

void main() {
  tree t = createTree(15);
  allocLoop(100000);
}

tree createTree(int depth) {
  tree t = alloc(tree);
  if (depth > 1) {
    t.left = createTree(depth-1);
    t.right = createTree(depth-1);
  }
  return t;
}

void allocLoop(int count) {
  while (count > 0) {
    tree t = alloc(tree);
    count = count-1;
  }
}