/*
 *  This file is part of the Jikes RVM project (http://jikesrvm.org).
 *
 *  This file is licensed to You under the Eclipse Public License (EPL);
 *  You may not use this file except in compliance with the License. You
 *  may obtain a copy of the License at
 *
 *      http://www.opensource.org/licenses/eclipse-1.0.php
 *
 *  See the COPYRIGHT.txt file distributed with this work for information
 *  regarding copyright ownership.
 */

/**
 * This is a simple test that checks hashCode values persist across a collection.
 */
void main() {
  int listSize = 200;
  int hashEvery = 20;

  object head = alloc(1, 1);
  head.int[0] = hash(head);
  object last = head;
  int i = 1;
  while (i < listSize) {
    object current = alloc(1, 1);
    if ((i % hashEvery) == 0) {
      current.int[0] = hash(current);
    }
    last.object[0] = current;
    last = current;
    i = i + 1;
  }
  verify(head);
  gc();
  verify(head);
}

void verify(object current) {
  while (current) {
    if (current.int[0] != 0) {
  	  assert(current.int[0] == hash(current), "Hash code does not match remembered value ", current.int[0], " ", hash(current));
  	}
  	current = current.object[0];
  }
}