/*
 *  This file is part of the Jikes RVM project (http://jikesrvm.org).
 *
 *  This file is licensed to You under the Common Public License (CPL);
 *  You may not use this file except in compliance with the License. You
 *  may obtain a copy of the License at
 *
 *      http://www.opensource.org/licenses/cpl1.0.php
 *
 *  See the COPYRIGHT.txt file distributed with this work for information
 *  regarding copyright ownership.
 */

/**
 * This is a simple test that allocates large objects.
 */
void main() {
  int limitPages = 32; // 128
  int startPages = 2;
  int p = startPages;
  while (p <= limitPages) {
    object temp = alloc(p*512, p * 512);
    gc();
    p = p + 2;
  }
}
