/*
 *  This file is part of the Jikes RVM project (http://jikesrvm.org).
 *
 *  This file is licensed to You under the Eclipse Public License (EPL);
 *  You may not use this file except in compliance with the License. You
 *  may obtain a copy of the License at
 *
 *      http://www.opensource.org/licenses/eclipse-1.0.php
 *
 *  See the COPYRIGHT.txt file distributed with this work for information
 *  regarding copyright ownership.
 */

/*
 * Allocate a single object and collect twice.  
 *
 * Remove the reference, and collect again.
 *
 * Note that due to shortcomings in the scripting engine (it has no liveness
 * analysis), returning from a function is the only way to guarantee
 * removal of any dangling references. (RJG - 27 May 2010)
 */
void main() {
  create();
  gc();
}

void create() { 
  object o = alloc(1,1); 
  gc();
  gc();
}

