/*
 *  This file is part of the Jikes RVM project (http://jikesrvm.org).
 *
 *  This file is licensed to You under the Common Public License (CPL);
 *  You may not use this file except in compliance with the License. You
 *  may obtain a copy of the License at
 *
 *      http://www.opensource.org/licenses/cpl1.0.php
 *
 *  See the COPYRIGHT.txt file distributed with this work for information
 *  regarding copyright ownership.
 */

/**
 * This is a simple test that forces an out of memory condition by creating an infinite linked list.
 */
void main() {
  expect(OutOfMemory);
  object current = alloc(1, 8);
  object last;
  while(true) {
    last = current;
    current = alloc(1,8);
    current.object[0] = last;
  }
}
