/*
 *  This file is part of the Jikes RVM project (http://jikesrvm.org).
 *
 *  This file is licensed to You under the Eclipse Public License (EPL);
 *  You may not use this file except in compliance with the License. You
 *  may obtain a copy of the License at
 *
 *      http://www.opensource.org/licenses/eclipse-1.0.php
 *
 *  See the COPYRIGHT.txt file distributed with this work for information
 *  regarding copyright ownership.
 */

option baseHeap "1024k";

void main() {
  other(1);
}

void other(int x) {
  print (tid(), " executing other(", x, ")" );
  object parent = alloc(5, 0);
  if (x < 30) {
    print(tid(), " spawning a thread");
    spawn(other, x + 1);
  }
  int i = 0;
  while (i < 5000) {
    object tmp;
    tmp = alloc(0, 100);
    parent.object[i % 5] = tmp;
    i = i + 1;
  }
  print(tid(), " done");
}
