/*
 *  This file is part of the Jikes RVM project (http://jikesrvm.org).
 *
 *  This file is licensed to You under the Common Public License (CPL);
 *  You may not use this file except in compliance with the License. You
 *  may obtain a copy of the License at
 *
 *      http://www.opensource.org/licenses/cpl1.0.php
 *
 *  See the COPYRIGHT.txt file distributed with this work for information
 *  regarding copyright ownership.
 */
 
 /*
  * MMTk test script.  Allocate a large object holding pointers to objects of a wide
  * (random) sizes.  Keep 100 live objects, and keep the newest objects
  * live.
  *
  * Highly non-generational :)  Basic exercise of multi-class allocation.
  */
void main() {
  int n = 10000;                  // Number of iterations
  int live = 200;                 // Number of live children
  int small = 5;                  // # scalars in the smallest object
  int large = 2000;               // # scalars in the largest object
  int i=0;
  
  object parent = alloc(live, 0, false);       // Parent object with 'live' pointers
  while (i < n) {             // loop for a while
    parent.object[i%live] = alloc(0, random(small,large), false);
    i = i + 1;                // loop counter
  }
}
