/*
 *  This file is part of the Jikes RVM project (http://jikesrvm.org).
 *
 *  This file is licensed to You under the Eclipse Public License (EPL);
 *  You may not use this file except in compliance with the License. You
 *  may obtain a copy of the License at
 *
 *      http://www.opensource.org/licenses/eclipse-1.0.php
 *
 *  See the COPYRIGHT.txt file distributed with this work for information
 *  regarding copyright ownership.
 */

/*
 * Run System.gc() many times.  Triggers some bugs in the
 * collection triggering code.
 */
void main() {
  gc();
  gc();
  gc();
  gc();
  gc();
  object list = null;
  int i=0;
  while (i < 64) {
    object tmp = alloc(1,0);
    tmp.object[0] = list;
    list = tmp;
    i = i + 1;
  }
  gc();
  gc();
  gc();
  gc();
  gc();
}


