/*
 *  This file is part of the Jikes RVM project (http://jikesrvm.org).
 *
 *  This file is licensed to You under the Eclipse Public License (EPL);
 *  You may not use this file except in compliance with the License. You
 *  may obtain a copy of the License at
 *
 *      http://www.opensource.org/licenses/eclipse-1.0.php
 *
 *  See the COPYRIGHT.txt file distributed with this work for information
 *  regarding copyright ownership.
 */

/*
 * Allocate a single object and collect.  Allocate a second one and collect.
 * Delete the second one, then the first one.
 *
 * Then do it in the reveres order.
 */
void main() {
  one_first();
  gc();
  one_second();
  gc();
}

void one_first() {
  object o = alloc(1,1);
  gc();
  two();
  gc();
}

void one_second() {
  two();
  object o = alloc(1,1);
  gc();
}

void two() {
  object o = alloc(2,2);
  gc();
}

