#!/bin/sh
#
# (C) Copyright IBM Corp. 2001
#
# $Id$
#
# @author Julian Dolby
#

#
# Run volano client simulator.
#
. $RVM_BUILD/environment

unset CLASSPATH

#
#
done=0
while [ $done = 0 ]; do
  
  case $1 in
    -jvm)
	JVM=$2
        shift 2
    ;;

    -classes)
	CLASSES="-classpath $2"
	shift 2
    ;;

    -procs)
	PROCS="-X:processors=$2"
	shift 2
    ;;

    -args)
	ARGS=$2
	shift 2
    ;;

    *)
	done=1
    ;;

  esac

done

#

if [ $JVM = jdk ]; then
  $HOST_JAVA_RT $CLASSES COM.volano.Mark $*

elif [ $JVM = jpn ]; then
  jalapeno $ARGS -X:h=200 -X:lh=100 $PROCS $CLASSES COM.volano.Mark $*

else
  echo "Usage: $0 [-jvm {jdk | jpn | j9} -procs n -classes <cp> -args <args>] <args>"
  exit 1

fi
