#! /bin/bash

#
# (C) Copyright IBM Corp. 2001
#
# $Id$
#
# This script will be the images needed by the Run-gather-dna script
#   Arguments:  directory to hold image directories
#                  ex BuildImages /u/hind/RVMSanityTests
#
# @author Michael Hind, Dec 1, 2001
#

# parent of build directories is command line argument to the script
BUILDDIR=$1
 
IMAGES='FastBaseAdaptiveCopyMS FastOpt0CopyMS FastOpt1CopyMS FastAdaptiveCopyMS'

for image in $IMAGES
do
   rm -rf $BUILDDIR/$image
   export RVM_BUILD=$BUILDDIR/$image
   echo "Configuring $image"
   jconfigure $image
   cd $BUILDDIR/$image
   echo "Building $image"
   jbuild -trace >RVM.trace 2>&1
done
